In [ ]:
# Import libraries

In [2]:
import torch
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
import PIL

# Tensors

## Creating tensors

Pytorch tensors are created using `torch.tensor()`

### scalar

In [ ]:
scalar_tensor = torch.tensor(2.4)
scalar_tensor

tensor(2.4000)

In [ ]:
scalar_tensor.ndim

0

In [ ]:
# Get scalar tensor back as Python int
scalar_tensor.item()

2.4000000953674316

### vector

In [ ]:
vector = torch.tensor([2, 4])
vector

tensor([2, 4])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

### MATRIX

In [ ]:
MATRIX = torch.tensor([[1, 2], [3, 4]])
MATRIX

tensor([[1, 2],
        [3, 4]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
NEW_TENSOR = torch.tensor([
    [[1, 2],[3, 4],[5, 6]],
    [[9, 8],[4, 5],[7, 8]]])
NEW_TENSOR

tensor([[[1, 2],
         [3, 4],
         [5, 6]],

        [[9, 8],
         [4, 5],
         [7, 8]]])

In [ ]:
NEW_TENSOR.shape

torch.Size([2, 3, 2])

### Random tensors

`torch.rand()` returns a tensor filled with random numbers from a uniform distribution on the interval [0,1)

In [ ]:
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.3032, 0.7373, 0.7363, 0.3043],
        [0.7932, 0.4568, 0.9402, 0.6331],
        [0.6750, 0.2324, 0.8268, 0.1430]])

torch.randint() returns a tensor filled with random integers generated uniformly between low (inclusive) and high (exclusive).

In [ ]:
random_image_tensor = torch.randint(low=0, high=256, size=(224, 224, 3))

In [ ]:
random_image_tensor.shape

torch.Size([224, 224])

`torch.normal()` returns a tensor of random numbers drawn from separate normal distributions whose mean and standard deviation are given.

In [ ]:
normal_tensor = torch.normal(0, 1, [3, 4])
normal_tensor

tensor([[ 0.5218,  0.6507,  0.4250, -0.6091],
        [-0.4760, -0.3344, -0.6256,  0.1752],
        [-1.4397, -0.6340,  0.8134,  0.2299]])

### Zeros and Ones

In [ ]:
zeros = torch.zeros(3, 4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones = torch.ones(2, 2)
ones

tensor([[1., 1.],
        [1., 1.]])

### Range of tensors and tensors-like

In [ ]:
# Range of tensors
one_to_ten = torch.arange(1, 11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# Tensors-like
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
# Tensors-like
five_two = torch.zeros(5, 2)
five_two_one_like = torch.ones_like(five_two)
five_two_one_like 

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])

## Tensor datatypes

**Note**: Tensor datatype is one of the 3 big errors with Pytorch and deep learning:
1. datatype
2. shape
3. device

In [ ]:
# int 64 tensor
int_64_tensor = torch.tensor([2, 3, 4])
int_64_tensor.dtype

torch.int64

In [ ]:
# Float 32 tensor
float_32_tensor = torch.tensor([2., 3., 4.])
float_32_tensor.dtype

torch.float32

In [ ]:
# Float 64 tensor
float_64_tensor = torch.tensor([2., 3., 4.], dtype=torch.float64)
float_64_tensor.dtype

torch.float64

In [ ]:
# Float 16 tensor
float_16_tensor = torch.tensor([2., 3., 4.], dtype=torch.float16)
float_16_tensor.dtype

torch.float16

In [ ]:
# Convert float32 to float16
new_float_32_tensor = torch.tensor([12., 23., 34.])
new_float_16_tensor = new_float_32_tensor.type(torch.float16)
new_float_16_tensor

tensor([12., 23., 34.], dtype=torch.float16)

In [ ]:
# Different dtypes calculating: int to float
a = int_64_tensor * float_64_tensor
a.dtype

torch.float64

In [ ]:
# Different dtypes calculating: small to large
a = float_16_tensor * float_64_tensor
a.dtype

torch.float64

## Get info from tensors
1. datatype - tensor.dtype
2. shape - tensor.shape
3. device - tensor.device

In [ ]:
# Create a tensor
some_tensor = torch.normal(1, 1, (2, 2))
some_tensor

tensor([[-2.3529,  0.3728],
        [-0.0385, -0.0033]])

In [ ]:
print(f"Datatype: {some_tensor.dtype}")
print(f"Shape: {some_tensor.shape}")
print(f"Size: {some_tensor.size()}")
print(f"Device: {some_tensor.device}")

Datatype: torch.float32
Shape: torch.Size([2, 2])
Size: torch.Size([2, 2])
Device: cpu


## Manipulating tensors

1. **Operations**
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Multiplication (MATRIX)

2. **Transpose**
3. **Aggregation**
4. **Reshaping, stacking, squeezing**

### Tensor Operations

In [ ]:
# Create tensors
tensor_one = torch.tensor([1, 2, 3])
tensor_two = t orch.tensor([10, 21, 32])
tensor_three =torch.tensor([[2],[3],[4]])

In [ ]:
# Addition
print(tensor_one + 10)
print(tensor_one + tensor_two)
print(torch.add(tensor_one, 10)) # Faster
print(torch.add(tensor_one, tensor_two)) # Faster

tensor([11, 12, 13])
tensor([11, 23, 35])
tensor([11, 12, 13])
tensor([11, 23, 35])


In [ ]:
# Subtraction
print(tensor_one - 10)
print(tensor_one - tensor_two)
print(torch.sub(tensor_one, 10)) # Faster
print(torch.sub(tensor_one, tensor_two)) # Faster

tensor([-9, -8, -7])
tensor([ -9, -19, -29])
tensor([-9, -8, -7])
tensor([ -9, -19, -29])


In [ ]:
# Multiplication (element-wise)
print(tensor_one * 10)
print(torch.mul(tensor_one, 10)) # Faster

tensor([10, 20, 30])
tensor([10, 20, 30])


In [ ]:
# Division
print(tensor_one / 10)
print(torch.div(tensor_one, 10)) # Faster

tensor([0.1000, 0.2000, 0.3000])
tensor([0.1000, 0.2000, 0.3000])


In [ ]:
# Multiplication (MATRIX)
print(tensor_one @ tensor_three) 
print(torch.matmul(tensor_one, tensor_three)) # Faster

tensor([20])
tensor([20])


In [ ]:
%%time
value = 0
for i in range(len(tensor_one)):
    value += tensor_one[i] * tensor_one[i]
print(value)

tensor(14)
CPU times: user 1.21 ms, sys: 14 µs, total: 1.22 ms
Wall time: 1.11 ms


In [ ]:
%%time
print(tensor_one @ tensor_one)

tensor(14)
CPU times: user 1.58 ms, sys: 818 µs, total: 2.4 ms
Wall time: 2.38 ms


In [ ]:
%%time
print(torch.matmul(tensor_one, tensor_one))

tensor(14)
CPU times: user 577 µs, sys: 0 ns, total: 577 µs
Wall time: 588 µs


### Tensor Transpose

In [ ]:
tensor_A = torch.rand(3, 2)
tensor_B = torch.rand(3, 2)
print(tensor_A)
print(tensor_B)

tensor([[0.9990, 0.0688],
        [0.7740, 0.7146],
        [0.4880, 0.0411]])
tensor([[0.6953, 0.5218],
        [0.2144, 0.8462],
        [0.1952, 0.5748]])


In [ ]:
torch.matmul(tensor_A, tensor_B) # Inner tensor shape not matched

RuntimeError: ignored

In [ ]:
print(tensor_B)
print(tensor_B.T)

tensor([[0.6953, 0.5218],
        [0.2144, 0.8462],
        [0.1952, 0.5748]])
tensor([[0.6953, 0.2144, 0.1952],
        [0.5218, 0.8462, 0.5748]])


In [ ]:
torch.matmul(tensor_A, tensor_B.T)

tensor([[0.7304, 0.2724, 0.2346],
        [0.9111, 0.7707, 0.5619],
        [0.3607, 0.1394, 0.1189]])

### Tensor Aggregation

In [ ]:
# Create a tensor
x = torch.arange(1, 11, dtype=torch.float32)
x

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
# Find the min
print(torch.min(x))
print(x.min())

tensor(1.)
tensor(1.)


In [ ]:
# Find the max
print(torch.max(x))
print(x.max())

tensor(10.)
tensor(10.)


In [ ]:
# Find the mean !! cannot be executed with long datatype
print(torch.mean(x))
print(x.mean())

tensor(5.5000)
tensor(5.5000)


In [ ]:
# Find the sum
print(torch.sum(x))
print(x.sum())

tensor(55.)
tensor(55.)


In [ ]:
# Find the positional min and max
y = torch.tensor([6, 2, 10, 18])
print(y.argmin())
print(y.argmax())

tensor(1)
tensor(3)


### Reshaping, stacking, squeezing

In [ ]:
# Creating a tensor
x = torch.arange(1, 11, dtype=torch.float32)
x

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
# Reshaping - reshape an input tensor to a defined shape
x_reshaped_one = x.reshape(2, 5)
x_reshaped_two = torch.reshape(x, (2, 5))
print(x_reshaped_one)
print(x_reshaped_two)

tensor([[ 1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10.]])
tensor([[ 1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10.]])


In [ ]:
# View - share the same memory as the orginal input tensor
x_view_one = x.view(2, 5)
print(x_view_one)
x_view_one[0, :] = 5
print(x_view_one)
print(x)

tensor([[ 1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10.]])
tensor([[ 5.,  5.,  5.,  5.,  5.],
        [ 6.,  7.,  8.,  9., 10.]])
tensor([ 5.,  5.,  5.,  5.,  5.,  6.,  7.,  8.,  9., 10.])


In [ ]:
# Stack tensors on top of each other, both tensors have to be the same size
x_stacked_0 = torch.stack([x, x, x], dim=0)
x_stacked_1 = torch.stack([x, x, x], dim=1)
print(x_stacked_0)
print(x_stacked_1)

tensor([[ 5.,  5.,  5.,  5.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 5.,  5.,  5.,  5.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 5.,  5.,  5.,  5.,  5.,  6.,  7.,  8.,  9., 10.]])
tensor([[ 5.,  5.,  5.],
        [ 5.,  5.,  5.],
        [ 5.,  5.,  5.],
        [ 5.,  5.,  5.],
        [ 5.,  5.,  5.],
        [ 6.,  6.,  6.],
        [ 7.,  7.,  7.],
        [ 8.,  8.,  8.],
        [ 9.,  9.,  9.],
        [10., 10., 10.]])


In [ ]:
a = torch.rand(3, 4)
b = torch.rand(3, 4)
stacked = torch.stack([a, b], dim = 2)
stacked, stacked.shape

(tensor([[[0.9015, 0.0945],
          [0.3713, 0.7358],
          [0.9611, 0.8343],
          [0.9472, 0.1474]],
 
         [[0.2131, 0.7186],
          [0.9883, 0.6566],
          [0.4658, 0.3388],
          [0.9232, 0.6826]],
 
         [[0.3505, 0.1320],
          [0.4019, 0.2694],
          [0.5101, 0.3875],
          [0.8441, 0.5727]]]), torch.Size([3, 4, 2]))

In [ ]:
# torch.squeeze() returns a tensor with all the dimensions of input of size 1 removed.
unsqueezed = torch.tensor([[1,2,3]])
print(unsqueezed.shape)
unsqueezed = torch.squeeze(unsqueezed)
print(unsqueezed.shape)
print(unsqueezed)

torch.Size([1, 3])
torch.Size([3])
tensor([1, 2, 3])


In [ ]:
# torch.unsqueeze() add a single dimension to a target tensor at a specific dim
x = torch.tensor([1,2,3])
print(f"Previous:{x}" )
x_unsqueezed = torch.unsqueeze(x, dim = 1)
print(f"after:{x_unsqueezed}")

Previous:tensor([1, 2, 3])
after:tensor([[1],
        [2],
        [3]])


In [ ]:
# torch.permute() returns a view of the original tensor input with its dimensions permuted.
x_orig = torch.rand(224, 224, 3) # [height, width, colour_channels]

x_permuted = torch.permute(x_orig, (2, 0, 1))
x_permuted.shape

torch.Size([3, 224, 224])

### Indexing

In [4]:
# Create a tensor
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]), torch.Size([1, 3, 3]))

In [5]:
x[0][1][1]

tensor(5)

In [7]:
x[0][:][2]

tensor([7, 8, 9])

### Numpy and Tensor

In [3]:
array = np.array([1, 2, 3])
array

array([1, 2, 3])

In [9]:
# Converting Numpy array to tensor
tensor = torch.from_numpy(array)
tensor

tensor([1, 2, 3])

In [10]:
array = tensor.numpy()
array

array([1, 2, 3])

## Reproducbility

In [12]:
# Create two random tensors
random_A = torch.rand(2, 2)
random_B = torch.rand(2, 2)
print(random_A)
print(random_B)
print(random_A == random_B)

tensor([[0.7865, 0.3521],
        [0.9016, 0.0224]])
tensor([[0.3346, 0.5605],
        [0.8965, 0.3312]])
tensor([[False, False],
        [False, False]])


In [16]:
# Set random seed
RANDOM_SEED = 7
torch.manual_seed(RANDOM_SEED)
random_C = torch.rand(3, 3)
torch.manual_seed(RANDOM_SEED)
random_D = torch.rand(3, 3)
print(random_C)
print(random_D)
print(random_C == random_D)

tensor([[0.5349, 0.1988, 0.6592],
        [0.6569, 0.2328, 0.4251],
        [0.2071, 0.6297, 0.3653]])
tensor([[0.5349, 0.1988, 0.6592],
        [0.6569, 0.2328, 0.4251],
        [0.2071, 0.6297, 0.3653]])
tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])


# Device

## Setup

In [3]:
# Check GPU status
!nvidia-smi

Thu Jul 28 13:21:28 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   51C    P8    10W /  70W |      3MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [5]:
# Check for GPU access with PyTorch
torch.cuda.is_available()

True

In [6]:
# Setup device agonstic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [7]:
# count number of devices
torch.cuda.device_count()

1

## Applying Tensors

In [9]:
 # Create a tensor
 tensor_X = torch.tensor([1, 2, 3])
 tensor_X.device

device(type='cpu')

In [10]:
# Move Tensors to GPU
tensor_X_GPU = tensor_X.to(device)

In [11]:
tensor_X_GPU.device

device(type='cuda', index=0)

In [17]:
# Tensors on GPU cannot be operated with Numpy, move them to cpu first
tensor_X_CPU = tensor_X_GPU.cpu()  # or tensor_X_CPU = tensor_X.to("cpu")
tensor_X_CPU.numpy()

array([1, 2, 3])